n1 = int(input('Insira um numero'))
print('{} vezes {} é: {}'.format(n1, 1, n1))
print('{} vezes {} é: {}'.format(n1, 2, n1 * 2))
print('{} vezes {} é: {}'.format(n1, 3, n1 * 3))
print('{} vezes {} é: {}'.format(n1, 4, n1 * 4))
print('{} vezes {} é: {}'.format(n1, 5, n1 * 5))
print('{} vezes {} é: {}'.format(n1, 6, n1 * 6))
print('{} vezes {} é: {}'.format(n1, 7, n1 * 7))
print('{} vezes {} é: {}'.format(n1, 8, n1 * 8))
print('{} vezes {} é: {}'.format(n1, 9, n1 * 9))
print('{} vezes {} é: {}'.format(n1, 10, n1 * 10))
