n = input('Digite o valor:')
print(type(n))
print("É um número?", n.isnumeric())
print("É verdadeiro ou falso?", n.isascii())
print("É um caractere?", n.isalpha())
print('Tem espaço?', n.isspace())
print('É um alfanumerico?', n.isalnum())
print('Todos os caracteres são minusculos?', n.islower())
print('Todos os caracteres são maisculos?', n.isupper())
print('Aceita perimetros?', n.isprintable())
print(('Esta capitalizada?', n.istitle()))
